version: '3'

services:
  viewer-web:
    container_name: viewer-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./viewer/web:/web
    ports:
      - 9001:80
    environment:
      APP_HOST: viewer-app
      APP_PORT: 9000
      NGINX_LOG_LEVEL: warn

  viewer-app:
    container_name: viewer-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./viewer/app:/app
