version: "3"

services:

  viewer-web:
    container_name: viewer-web
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/use_an_lpa/web:latest
    build:
      context: .
      dockerfile: service-front/docker/web/Dockerfile
    volumes:
      - ./service-front/web:/web
    ports:
      - 9001:80
    environment:
      APP_HOST: viewer-app
      APP_PORT: 9000
      NGINX_LOG_LEVEL: warn

  viewer-app:
    container_name: viewer-app
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/use_an_lpa/viewer_front:latest
    build:
      context: .
      dockerfile: service-front/docker/app/Dockerfile
    volumes:
      - ./service-front/app:/app
    environment:
      # Always required
      KMS_SESSION_CMK_ALIAS: 'alias/viewer-sessions-cmk-alias'

      # Local only
      AWS_ENDPOINT_KMS: http://kms:8080
      AWS_ACCESS_KEY_ID: '-'
      AWS_SECRET_ACCESS_KEY: '-'
      ENABLE_XDEBUG: 'true'
      PHP_IDE_CONFIG: serverName=viewer-app
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1 remote_log=/tmp/xdebug.log

  viewer-composer:
    image: composer
    volumes:
      - ./service-front/app:/app
    command:
      - install
      - --prefer-dist
      - --no-suggest
      - --no-interaction
      - --no-scripts
      - --optimize-autoloader

  localstack:
    image: localstack/localstack
    ports:
      - 4569:4569
    environment:
      - SERVICES=dynamodb:4569
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME=localstack

  local-config:
    container_name: local-config
    build:
      context: .
      dockerfile: local-config/Dockerfile
    volumes:
      - ./local-config:/config
    depends_on:
      - localstack

  kms:
    image: nsmithuk/local-kms:2
    volumes:
      - ./local-config:/init
    environment:
      REGION: eu-west-1
      SEED_PATH: /init/kms-seed.yaml
